version: '3'
services:
  app: &base
    container_name: docker_app
    build: .
    volumes:
      - ./:/myapp
      - bundle_install:/myapp/vendor/bundle
      - node_modules:/myapp/node_modules
      - tmp_cache:/myapp/tmp/cache
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      BUNDLE_APP_CONFIG: /myapp/.bundle
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: development
      CACHE_STORE_URI: redis://redis:6379/0/cache
      SESSION_STORE_URI: redis://redis:6379/0/session
  spring:
    <<: *base
    container_name: docker_spring
    command: ["/root/docker-scripts/spring.sh"]
    ports: []
  mysql:
    container_name: docker_mysql
    image: "mysql:5.6"
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    container_name: docker_redis
    image: "redis"
    ports:
      - "6379:6379"
volumes:
  tmp_cache:
    driver: local
  mysql_db:
    driver: local
  bundle_install:
    driver: local
  node_modules:
    driver: local
